# -*- coding: utf-8 -*-
"""YOLOv8_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cuc5NER7qsVCFlZ2WF2TdMk3z0E4w6wV

**YOLOV8**
"""

!unzip '/content/drive/MyDrive/SixrayTraining.v1i.yolov8.zip'

from google.colab import drive
drive.mount('/content/drive')

"""*Downloading different versions of Yolo*"""

pip install ultralytics

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

model2 = YOLO('yolov8n.pt')

results = model2.train(data = 'data.yaml', imgsz=540, epochs= 50, batch= -1, name= 'yolov8n_custom')

# Load our custom goat model
model = YOLO("/content/runs/detect/yolov8n_custom/weights/best.pt")
# Use the model to detect object - goat
model.predict(source="/content/test/images", save=True, show=True)

# Load our custom goat model
model = YOLO("/content/runs/detect/yolov8n_custom/weights/best.pt")
# Use the model to detect object - goat
model.predict(source="/content/test/images", save=True, show=True)